<?php

/**
 * Full-text Searche Modes
 */
define('NATURAL_LANGUAGE', 'IN NATURAL LANGUAGE MODE');
define('NATURAL_LANGUAGE_QUERY', 'IN NATURAL LANGUAGE MODE WITH QUERY EXPANSION');
define('BOOLEAN_MODE', 'IN BOOLEAN MODE');
define('QUERY_EXPANSION', "WITH QUERY EXPANSION");